name: Check README Links

on:
  push:
  pull_request:
    paths:
      - 'README.md'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at 00:00 UTC

jobs:
  check-push-count:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.push_count.outputs.should_run }}
      commits_until_next: ${{ steps.push_count.outputs.commits_until_next }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: push_count
        run: |
          PUSH_COUNT=$(git rev-list --count HEAD)
          SHOULD_RUN=$((PUSH_COUNT % 10 == 0))
          COMMITS_UNTIL_NEXT=$((10 - (PUSH_COUNT % 10)))
          echo "Push count: $PUSH_COUNT"
          echo "should_run=$SHOULD_RUN" >> $GITHUB_OUTPUT
          echo "commits_until_next=$COMMITS_UNTIL_NEXT" >> $GITHUB_OUTPUT

  check-links:
    needs: check-push-count
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' && needs.check-push-count.outputs.should_run == 'true')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Markdown Link Check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
        file-path: './README.md'
    - name: Update README with check info
      run: |
        LAST_CHECKED=$(date +'%Y-%m-%d')
        COMMITS_UNTIL_NEXT=${{ needs.check-push-count.outputs.commits_until_next }}
        sed -i 's/Last checked on: .*/Last checked on: '"$LAST_CHECKED"'/' README.md
        sed -i 's/Commits until next check: .*/Commits until next check: '"$COMMITS_UNTIL_NEXT"'/' README.md
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update link check info in README" && git push)
