name: Update README and Check Links

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    paths:
      - 'README.md'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at 00:00 UTC

jobs:
  update-readme-and-check-links:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      
      - name: Check commit message and update README
        id: check_commit
        run: |
          LATEST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $LATEST_COMMIT_MSG == *"-check"* ]]; then
            echo "CHECK_LINKS=true" >> $GITHUB_OUTPUT
            echo -e "\nLast checked on: $(date +'%Y-%m-%d')" >> README.md
            echo -e "\nCommits until next check: 0" >> README.md
          else
            PUSH_COUNT=$(git rev-list --count HEAD)
            COMMITS_UNTIL_NEXT=$((10 - (PUSH_COUNT % 10)))
            if [ $COMMITS_UNTIL_NEXT -eq 10 ]; then
              COMMITS_UNTIL_NEXT=0
            fi
            echo "CHECK_LINKS=$([ $COMMITS_UNTIL_NEXT -eq 0 ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
            sed -i '/Commits until next check:/d' README.md
            echo -e "\nCommits until next check: $COMMITS_UNTIL_NEXT" >> README.md
          fi

      - name: Commit README changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README [skip ci]" && git push)

      - name: Run Linkspector
        if: steps.check_commit.outputs.CHECK_LINKS == 'true'
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

      - name: Update README after successful link check
        if: steps.check_commit.outputs.CHECK_LINKS == 'true' && success()
        run: |
          sed -i '/Last checked on:/d' README.md
          echo -e "\nLast checked on: $(date +'%Y-%m-%d')" >> README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update link check date in README [skip ci]" && git push)